name: ecommerce_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.1.1
  lottie: ^3.1.0
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  app_links: ^6.1.4
  provider:
dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - .env
  fonts:
    - family: TikTokSans
      fonts:
        - asset: assets/fonts/TikTokSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/TikTokSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/TikTokSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TikTokSans-Bold.ttf
          weight: 700
