name: ecommerce_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  loading_animation_widget: ^1.2.0
  googleapis_auth: ^1.6.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_local_notifications: ^17.2.0
  device_info_plus: ^9.1.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  step_progress_indicator: ^1.0.2
  dio: ^5.9.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.13.1
  http: ^1.2.2
  drop_down_list: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.1.1
  lottie: ^3.1.0
  supabase_flutter: ^2.3.4
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  app_links: ^6.1.4
  provider:
  intl: ^0.19.0
  uuid: ^4.5.0
  image_picker: ^1.0.4
  badges: ^3.1.2
  curved_navigation_bar: ^1.0.3
dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/credentials/
    - .env
  fonts:
    - family: TikTokSans
      fonts:
        - asset: assets/fonts/TikTokSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/TikTokSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/TikTokSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TikTokSans-Bold.ttf
          weight: 700
